### ISSUE TITLE
Organisations/repos

### ISSUE THREAD

**Issue by eine** [BSVLang/Main#2]
I am curious about why the language is hosted in a repo under BSVLang user's namespace and the Bluespec Compiler is hosted under the namespace of B-Lang-org (https://github.com/B-Lang-org/bsc). @rsnikhil, any hint?

**Comment by rsnikhil** [comment]
This is a temporary situation.  We've always considered the _language_ to be open, though the bsc compiler implementation to be proprietary (in fact, we offered to donate the whole language spec to IEEE SystemVerilog almost ten years ago, but they did not accept it).  bsc has also always been free to Universities, since the beginning (2004-ish). So, we put out language specs, tutorials, etc in the BSVLang repo a long time ago.  Now that bsc is open-sourced (as of a few days ago), we'll move the BSVLang stuff into the same repo soon.  Thanks for your patience.

**Comment by eine** [comment]
@rsnikhil, thanks a lot for your quick reply and insight. Note that there is no hurry at all, since it makes sense now that I know the motivation. Please, let me keep this issue open meanwhile, so that other users can easily find it. Actually, since I'm not a native speaker, it'd be good if anyone proposed a more descriptive and natural title for this issue.

**Comment by rsnikhil** [comment]
No problem.  I will actually move the explanation I gave, including the intention to move this repo's contents into the B-Lang.org repo, into the README, so it is clear to anyone who visits the site.  Thanks.
